### ISSUE TITLE
new method request - write to file-like object

### ISSUE THREAD

**Issue by backenders-game** [Pythonity/python-ivona-api#1]
writing to disk not always needed.

**Comment by backenders-game** [comment]
made  a pr  https://github.com/Pythonity/python-ivona-api/pull/2/files  - take a look.

**Comment by pawelad** [comment]
@Sorrow2 Cool, thanks for the report and the PR.

In general I agree, but would do you think about keeping it in one method like before, but accepting both path string and a file object, then do a simple if and write the content accordingly? Would you be open to do that?

**Comment by pawelad** [comment]
Fixed in version 0.2.0 as I agree that operating on file objects is a more flexible approach.
